os: linux
dist: xenial
language: python
cache: pip

# python and env.jobs are crossed to create the base build matrix
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
env:
  global:
    - INSTALL_TYPE="pip"
    - SETUP_REQUIRES="--upgrade pip setuptools wheel"
    - NIGHTLY_WHEELS="https://pypi.anaconda.org/scipy-wheels-nightly/simple"
    - CHECK_TYPE="travis_tests"
    - OSX_MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
  jobs:
    - EXTRA_PIP_FLAGS=""
    - EXTRA_PIP_FLAGS="--pre --extra-index-url $NIGHTLY_WHEELS"

# Add OSX entries to the build matrix
jobs:
  include:
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.8
    - python: 3.6
      env: CHECK_TYPE=tutorial
    - python: 3.6
      env: CHECK_TYPE=doc
    - python: 3.6
      env: INSTALL_TYPE=sdist
    - python: 3.6
      env: INSTALL_TYPE=wheel
    # Minimal setup requirements
    - python: 3.6
      env:
        - SETUP_REQUIRES="pip==10.0.1 setuptools==30.4.0"
        - CHECK_TYPE=skiptests
  exclude:
    - python: 3.5
      env: EXTRA_PIP_FLAGS="--pre --extra-index-url $NIGHTLY_WHEELS"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export MINICONDA=$HOME/miniconda;
        export PATH="$MINICONDA/bin:$PATH";
        hash -r;
        echo $OSX_MINICONDA_URL;
        wget $OSX_MINICONDA_URL -O miniconda.sh;
        bash miniconda.sh -b -s -f -p $MINICONDA;
        conda config --set always_yes yes;
        conda info -a;
        conda install --quiet python=$PYTHON_VERSION;
        hash -r;
      fi
    - travis_retry pip install --upgrade pip virtualenv
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python --version # just to check
    - travis_retry pip install $SETUP_REQUIRES
    # Build package
    - |
      if [ "$INSTALL_TYPE" == "sdist" ]; then
        python setup.py egg_info  # check egg_info while we're here
        python setup.py sdist
        export ARCHIVE=$( ls dist/*.tar.gz )
      elif [ "$INSTALL_TYPE" == "wheel" ]; then
        python setup.py bdist_wheel
        export ARCHIVE=$( ls dist/*.whl )
      elif [ "$INSTALL_TYPE" = "pip" ]; then
        export ARCHIVE="."
      fi
    - |
      if [ "${ARCHIVE:0:5}" = "dist/" ]; then
        pip install twine
        twine check $ARCHIVE
      fi

install:
    # analysis extra existed and people may have it in their dependencies, so
    # install it to make sure we don't remove it (unintentionally)
    - travis_retry pip install $EXTRA_PIP_FLAGS "$ARCHIVE[analysis]"
    # Basic import check; ensures import doesn't depend on any extras
    - python -c 'import bids; print(bids.__version__)'
    - if [ "$CHECK_TYPE" == "skiptests" ]; then exit 0; fi

before_script:
    # Because pybids is already installed, will just look up the extra
    - travis_retry pip install $EXTRA_PIP_FLAGS "pybids[$CHECK_TYPE]"

script:
    - make $CHECK_TYPE

after_script:
    - codecov --file cov.xml --flags unittests

deploy:
  provider: pypi
  username: $PYPI_USER
  password: $PYPI_PASS
  distributions: "-q sdist bdist_wheel"
  skip_existing: true
  edge: true
  on:
    tags: true
