version: 2
jobs:
  build_docs:
    docker:
      - image: python:3.7.4
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: |
            python -m venv /tmp/venv
            source /tmp/venv/bin/activate
      - run:
          name: Check Python version and upgrade pip
          command: |
            source /tmp/venv/bin/activate
            which python
            python --version
            python -m pip install --upgrade pip setuptools
      - run:
          name: Install PyBIDS
          command: |
            source /tmp/venv/bin/activate
            python -m pip install -e ".[doc]"
      - run:
          name: Build documentation
          command: |
            source /tmp/venv/bin/activate
            make -C doc html
      - store_artifacts:
          path: /root/project/doc/_build/html
      - persist_to_workspace:
          root: doc/_build
          paths: html

  deploy_docs:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: doc/_build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.2
            git config user.email "bids-maintenance@gmail.com"
            git config user.name "BIDS Maintenance"
      - add_ssh_keys:
          fingerprints:
            - "b1:24:94:8c:32:93:b9:46:48:42:77:1e:00:dc:d2:d"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            TIMESTAMP=$(date)
            gh-pages --dotfiles --message "pybids docs built with Sphinx on $TIMESTAMP [skip ci]" --dist doc/_build/html


# https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docs:
          filters:
            tags:
              only: /.*/
      - deploy_docs:
          requires:
            - build_docs
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
